### ISSUE TITLE
selected sample 0

### ISSUE THREAD

**Issue by mh2537** [pauliacomi/pyGAPS#11]
just installed pygaps. import pgaps command gives:
0 selected samples
23 adsorbates

**Comment by pauliacomi** [comment]
That is standard behaviour. It means that the internal database has 0 materials (that is because you have not added any of your own samples) and 23 adsorbates (standard gasses/vapours, like nitrogen, methane, water etc.). 

It is just a check at the start. Did you manage to create an isotherm?

**Comment by mh2537** [comment]
Thanks for the reply. I am afraid I haven’t managed to do that . At what stage should I define the sample? What does the file content look like ? How is it formatted?

**Comment by pauliacomi** [comment]
I suggest you first have a look at the extensive [manual](https://pygaps.readthedocs.io/en/master/manual/isotherm.html#creating-an-isotherm) and the [quickstart](https://pygaps.readthedocs.io/en/master/examples/quickstart.html). The quickstart and many other examples are actually Jupyter notebooks which can be found in the [examples folder](https://github.com/pauliacomi/pyGAPS/tree/master/docs/examples), so you can download them and have a starting base for your code.

Also, unless you plan on storing your isotherms in a database, there should be no need to define specific samples.

Let me know how it goes.

**Comment by mh2537** [comment]
I got it right all the way through!
Thanks

**Comment by pauliacomi** [comment]
Did everything work out ok? If so, please close this issue or let me know if I can be of further help.

**Comment by mh2537** [comment]
Hi 
It works fine now as I said in my earlier email but I think I don’t know how to close the thread in the forum.
Best 
Masoud

**Comment by pauliacomi** [comment]
It's okay, I've got it.
