### ISSUE TITLE
ASK

### ISSUE THREAD

**Issue by ERIC94067** [pauliacomi/pyGAPS#18]
I want to know what PRESSURE in this picture means PRESSURE

https://pygaps.readthedocs.io/en/master/examples/iast.html
IN[4]'s Picture

**Comment by pauliacomi** [comment]
Hi @gray94067 , the x-axis in the selectivity_v_pressure graph (SVP) is the **total** pressure of the binary mixture. Was this your question?

**Comment by ERIC94067** [comment]
YES it is what I ask

**Comment by pauliacomi** [comment]
Then I will go ahead and close this question.
