### ISSUE TITLE
python run error

### ISSUE THREAD

**Issue by wilson0806** [pauliacomi/pyGAPS#19]
Why does an error occur after entering my data?
error1 is the error that ran out after I entered the data
error2 is after running out of the loading-pressure chart

![error1](https://user-images.githubusercontent.com/71698514/93865775-5c129780-fcf9-11ea-87ec-e0d25205d4c5.png)
![error2](https://user-images.githubusercontent.com/71698514/93865781-5d43c480-fcf9-11ea-8f6f-b1319fd5c7b7.png)

**Comment by pauliacomi** [comment]
Hi @wilson0806, 

It looks to me like your data is string rather than numeric but since you give no further details I can't give you more advice. 

I suggest you fill in this [issue template](https://github.com/pauliacomi/pyGAPS/issues/new?assignees=&labels=bug&template=bug_report.md).
