### ISSUE TITLE
python run error

### ISSUE THREAD

**Issue by wilson0806** [pauliacomi/pyGAPS#20]
**Describe the bug**
1.     CalculationError: Root finding for adsorbed phase mole fractions failed.
        This is likely because the default guess is not good enough.
        Try a different starting guess for the adsorbed phase mole fractions by
        passing an array adsorbed_mole_fraction_guess to this function. Scipy error
        message: Number of calls to function has reached maxfev = 400.
2.     TypeError: unsupported operand type(s) for -: 'str' and 'str'
**To Reproduce**
- Code sample
- Error output
I use the sample program, change the material to carbon and my experimental data, and execute python.
chart is the output after running
**Expected behavior**
I hope that all can simulate the model smoothly, calculate the selectivity and draw the chart.
**Screenshots**
![error1](https://user-images.githubusercontent.com/71698514/93877408-fdeeb000-fd0a-11ea-9207-e25f8d501949.PNG)
![error1_data_N2](https://user-images.githubusercontent.com/71698514/93877410-ffb87380-fd0a-11ea-82d4-6d2240354849.PNG)
![error1-data-CO2](https://user-images.githubusercontent.com/71698514/93877412-ffb87380-fd0a-11ea-99c5-fe1a3d64d382.PNG)
![error1-Figure_1](https://user-images.githubusercontent.com/71698514/93877414-00510a00-fd0b-11ea-9dd6-c7cc04b15401.png)
![error1-Figure_2](https://user-images.githubusercontent.com/71698514/93877416-00e9a080-fd0b-11ea-80b6-596c638bd2d1.png)
![error2](https://user-images.githubusercontent.com/71698514/93877418-00e9a080-fd0b-11ea-8124-52c977666413.png)
![error2-data CO2](https://user-images.githubusercontent.com/71698514/93877420-01823700-fd0b-11ea-8385-e0e6fba1b197.PNG)
![error2-data N2](https://user-images.githubusercontent.com/71698514/93877421-021acd80-fd0b-11ea-8069-acb55af58252.PNG)

**System (please complete the following information):**
 - OS: [e.g. Windows/Linux/MacOS]
 - Python Version [e.g. Python 3.6]
 - Toolchain [e.g. Conda, virtualenv]
 OS:Windows 
 Python Version:Python3.7

**Additional context**

**Comment by pauliacomi** [comment]
Hi @wilson0806, your last point for the second isotherm seems off (14000 bar), could you check it?

**Comment by pauliacomi** [comment]
I will close this as no further communication.
