### ISSUE TITLE
ASK

### ISSUE THREAD

**Issue by ERIC94067** [pauliacomi/pyGAPS#21]
![擷取](https://user-images.githubusercontent.com/70583316/94409255-80162300-01a8-11eb-9e6c-5f9078708661.PNG)

I want to ask what are the ads and des mean in the picture, and the P/P^0 meaning, thanks

**Comment by pauliacomi** [comment]
They are "adsorption" and "desorption" branches while p/p0 is relative pressure, as in absolute pressure divided by adsorbate vapour pressure at the isotherm tempererature.

To familiarise yourself with the basics of adsorption theory and notation I recommend this book: *J. Rouquerol, F. Rouquerol, P. L. Llewellyn, G. Maurin, and K. Sing, Adsorption by powders and porous solids : principles, methodology and applications. 2013.*
