### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by wilson0806** [pauliacomi/pyGAPS#22]
![Figure_1](https://user-images.githubusercontent.com/71698514/95070019-1498fc00-073a-11eb-8624-19a61137a975.png)
![Figure_2](https://user-images.githubusercontent.com/71698514/95070021-1793ec80-073a-11eb-82c0-ab0c3316edde.png)
Figure 1 use the model BET to  run the python by my data.
Figure 2 use the model Langmuir to  run the python by my data.
Why are selective charts different using the same data?

![Figure_3](https://user-images.githubusercontent.com/71698514/95071680-a6a20400-073c-11eb-9ea4-4afd9540b3b7.png)
What do these symbols mean?

**Comment by pauliacomi** [comment]
The two different models fit your data in a different way, which means you will get different results when estimating selectivity.

Output is just the values for each component's partial pressure, calculated spreading pressure, estimated loading and total fraction.

**Comment by wilson0806** [comment]
Thanks.

**Comment by pauliacomi** [comment]
No problem, I will close this issue then.
