### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by wilson0806** [pauliacomi/pyGAPS#24]
![Figure_2](https://user-images.githubusercontent.com/71698514/96331616-42af0200-1091-11eb-8f65-449912d832b0.png)
How can I change the upper and lower limits of the y-axis?
Can I change the pressure unit bar to kpa?
How to change?

**Comment by pauliacomi** [comment]
The graph is just a matplotlib plot, you can use standard matplotlib commands with it.
You can also pass a previously-created matplotlib ax object to the function and customize it afterwards.
```
import matplotlib.pyplot as plt
fig, ax1 = plt.subplots(1)
result_dict = iast_binary_svp(..., ax=ax1)
# customize fig/ax1
fig.show()
```
As for the conversion, the function returns a dictionary with the plotted values. You can take them and do with them as you wish.

```
print(results)
```

**Comment by wilson0806** [comment]
Thanks!
