### ISSUE TITLE
Error in IAST calculation with certain models

### ISSUE THREAD

**Issue by ERIC94067** [pauliacomi/pyGAPS#25]
I use all model but nothing can run selectivity 
I want to ask why ?
![1603731616324](https://user-images.githubusercontent.com/70583316/97204440-0a29c980-17f1-11eb-8a53-868233d60b87.jpg)
![1603731641748](https://user-images.githubusercontent.com/70583316/97204443-0bf38d00-17f1-11eb-81fc-fedfb9baaf0d.jpg)
![1603731665093](https://user-images.githubusercontent.com/70583316/97204449-0d24ba00-17f1-11eb-8f61-b51e74027593.jpg)

**Comment by pauliacomi** [comment]
Some of the models (such as Freundlich) are unsuitable for use with IAST as they are inconsistent with Henry's law at the limit towards infinite dilution.

As for the other errors here, it is likely a function of the data used, so I cannot guess. If you want to discuss in detail, email me at my personal address.
