### ISSUE TITLE
loading unit in cm3(STP)

### ISSUE THREAD

**Issue by NicolaiHaaberJunge** [pauliacomi/pyGAPS#27]
Hi, 

**Is your feature request related to a problem? Please describe.**
I am working on incorporating pyGAPS into a local tool to be used in my research group for gas adsorption measurements. However I stumbled upon a source of unclearity with pyGAPS (at least to me. See https://pygaps.readthedocs.io/en/master/manual/units.html?highlight=STP). I assumed the PointIsotherm used STP as loading_unit but this it not the case. So I need convert our adsorption data to real conditions before using pyGAPS. This of course means that the plotted isotherms have different y-axis scaling. We have a lot of old isotherm data that we often reference. For us, it is therefore preferred to have the option of using "cm3(STP)".

**Describe the solution you'd like**
Add STP alternative to available loading units.

Otherwise I really like pyGAPS and find it very usefull.

P.S I understand that there are different opinions on whether to use STP or real conditions.

**Comment by pauliacomi** [comment]
Hi NicHaaJun,

I believe you can do what you wish by using:

```
iso = pygaps.PointIsotherm(
     loading=[],
     pressure=[],
     loading_basis="molar",
     loading_unit="cm3(STP)",
)
```

Keep in mind, when reporting an isotherm on STP, pyGAPS is using a molar basis, since it's assuming ideal gas behaviour ( V[STP] = P/nRT ).

I hope I understood your question?

All the best,
Paul

**Comment by NicolaiHaaberJunge** [comment]
Hi Paul,

Yes that worked. Thank you for such a fast response!

I thought I could do:

`
iso = pygaps.PointIsotherm(
     loading=[],
     pressure=[],
     loading_basis="volume",
     loading_unit="cm3(STP)",
)
`

I simply misunderstood.


Best,
Nicolai

**Comment by pauliacomi** [comment]
Hi Nicolai,

Yes, I can see it being a bit confusing. I made the choice based on what made sense from the programming side. I will consider highlighting this in the manual.

By the way, you can permanently convert the isotherms to "real" volume if you do something like:

```
iso.convert(loading_basis="volume", loading_unit="cm3")
```

I will close this now, if that's ok. Don't hesitate to contact me if you have any other questions.

-pi

**Comment by pauliacomi** [comment]
By the way @NicHaaJun , may I ask where you are from? I am always curious to hear how and where pyGAPS is used!
-pi

**Comment by NicolaiHaaberJunge** [comment]
Sure, I am a PhD student at the University of Oslo in the section of heterogeneous catalysis. Although I don't do extensive adsorption characterisation for my research (other than routine work) we have people in the group who do. For a long time commercial software has been used for this. But, being a python enthusiast and due to the never ending problem of commercial software licensing, I decided to build a simple interactive tool based on pyGAPS and ipywidgets for doing simple adsorption analysis. Many of us in the group do routine analysis work. 

Btw I do have a question about how pyGAPS chooses the pressure range based on the roq rules. As I understand it you do not get an unambiguous answer but typically multiple and slightly different pressure range segments that qualify. So, how does pyGAPS choose from these ranges.

Again I really enjoy pyGAPS and I think it is a great initiativ! 

/Nicolai

**Comment by pauliacomi** [comment]
I see, nice to make your acquaintance Nicolai, a new place on the map I can mark! Also, regarding your development of a GUI, that's a noble goal, and pretty much how pyGAPS started during my own PhD. Have you considered publishing and/or making it open source, it would be a boon for the community?

For the Rouquerol pressure range determination, I am using the classical rules as originally envisaged: (i) positive C constant, (ii) increasing region of Rouquerol plot and (iii) statistical monolayer location in chosen region. I am assuming that you have seen the recent paper from the group of David Fairen-Jimenez regarding their BETSI procedure which performs a multiple fitting routine in this region. This is a fantastic approach that is now possible with the "low cost" of computing power. 

The difference is essentially either taking the **whole** applicable range (rouquerol) or the **best consistent subset** of that applicable range (betsi). This has the advantage of removing obvious outlier points which would not be detected by the original method and converging to a "best case" scenario automatically. A trained operator *should* spot these issues and tweak the method to make the same choices...but this is just wishful thinking. Hopefully one day this approach could also be implemented in pyGAPS.

-pi
