### ISSUE TITLE
Documentation: Modelling in pyGAPS

### ISSUE THREAD

**Issue by sblanky** [pauliacomi/pyGAPS#29]
[In the list of models](https://pygaps.readthedocs.io/en/master/manual/modelling.html#modelling-in-pygaps), all are given in lower case. From my implementation, they don't actually work like that `Not all models provided correspond to internal models`

It does work if you use the appropriate case though i.e. `'Langmuir', 'DSLangmuir', 'GAB'`.

Documentation could be updated to reflect this.

Thanks, 
Scott

**Comment by pauliacomi** [comment]
Thanks for pointing it out.
Maybe it would be best if the case shouldn't matter, so you could pass any of `Langmuir`, `LANGMUIR` or `LaNgMuIr`. 
How does that sound?
-pi

**Comment by sblanky** [comment]
That does sound like the best option!

**Comment by pauliacomi** [comment]
Should be fixed by https://github.com/pauliacomi/pyGAPS/commit/cc869bf2c1a8a8409dbcd179dcdcf3c967dd44c8
