### ISSUE TITLE
Problem  while using ads to calculate mesopore psd

### ISSUE THREAD

**Issue by Loturest** [pauliacomi/pyGAPS#32]
Hi, it is an excellent package and I tried to use it to do some mesopore psd recently.

And, while using des data, the psd result is accord with that from ASIQWin, however, while using ads data, the result retrieved from pyGAPS  shows some discrepancy. 

Take the example of MCM-41, the parameters are set as  "pygaps-DH, ads , cylinder, Harkins/Jura, Kelvin...",  and the psd result is pasted as below:
[ 0.00201822,  0.00225409,  0.00259436,  0.00289094,  0.00346204,
        0.00396423,  0.0049243 ,  0.00587327,  0.00698337,  0.00815182,
        0.00949746,  0.01108028,  0.01263511,  0.01517044,  0.01848789,
        0.0291542 ,  0.07086728,  0.1233178 ,  0.18424804,  0.60479161,
        1.85880254,  0.55589063, -0.02554979, -0.09701637, -0.11233047,
       -0.12062342, -0.12620523, -0.11850983, -0.1186818 , -0.12019221,
       -0.10783947, -0.08993325, -0.06326952, -0.01934559,  0.06178637,
        0.20850592,  0.49788791,  0.95116182,  1.4317689 ,  0.43147767]
We can see many negative values in the above psd result, and it is weired.

After I checked the src code (pasted as follow), I found that a  different Kelvin_radius equation was used while using ads data, because the meniscus geometry of ads and des  is different. 

> def kelvin_radius()
>     if branch == 'ads':
>         if pore_geometry == 'cylinder':
>             m_geometry = 'cylindrical'
>         elif pore_geometry == 'sphere':
>             m_geometry = 'hemispherical'
>         elif pore_geometry == 'slit':
>             m_geometry = 'hemicylindrical'
> ...
>     elif branch == 'des':
>         if pore_geometry == 'cylinder':
>             m_geometry = 'hemispherical'
>         elif pore_geometry == 'sphere':
>             m_geometry = 'hemispherical'
>         elif pore_geometry == 'slit':
>             m_geometry = 'hemicylindrical'
> 
>     return - (2 * adsorbate_surface_tension * adsorbate_molar_density) / \
>         (geometry_factor * constants.gas_constant * temperature * numpy.log(pressure))

It is interesting, does anyone has any idea about that the ads/des have different "meniscus geometry"? 

update: I figured it out. ASIQWin and others just treated ads as des.
Maybe the package can add a new option which allows us to treat ads as des while calculating psd.

**Comment by pauliacomi** [comment]
Hi there,

Yes, the meniscus geometry, or the shape of the fluid-gas interface as shown in the photo below from **Adsorption by powders and porous solids** by Rouquerol et al, is generally regarded as different based on where the process starts, adsorption (pores empty) or desorption (pores full).

![image](https://user-images.githubusercontent.com/9705355/167298030-69eb5074-909b-456e-a7d3-6e00966985f8.png)

If we imagine an infinite cylindrical pore open at both sides, during adsorption the adsorbed phase forms a layer on the walls of the cylinder. The interface is then essentially just a smaller cylinder with a radius of `pore_radius - 2 * layer thickness`, like in the upper part of the figure.

However, during desorption, what happens is that the pore is filled, and the the interface is essentially just the "edges" of the filled pore, which take a (more or less) hemispherical shape, like in the lower part of the figure.

Now I do not know why ASIQWin would choose the same meniscus geometry for both adsorption and desorption, as it would seem to me as that would give wrong results. This is actually one of the reasons why I hope pyGAPS would be useful, you can look in the code and find out exactly what the calculation does! The negative values are a bit odd, I will look into that but I think it's just deviation from ideality.

As for your question, you can actually use any meniscus geometry if you get one of the lower level functions from `psd_meso.py`. You'll need manual values for some of the parameters. For example for the `pygaps-DH` model:

```
import pygaps as pg
from pygaps.characterisation.models_kelvin import get_kelvin_model
from pygaps.characterisation.models_thickness import get_thickness_model
from pygaps.characterisation.psd_meso import psd_pygapsdh

### Change these as you see fit
isotherm = pg.PointIsotherm() # Your isotherm here
branch = "ads"
thickness_model = "Harkins/Jura"
kelvin_model = "Kelvin"
pore_geometry = "cylinder"
meniscus_geometry = "cylindrical"
###

molar_mass = isotherm.adsorbate.molar_mass()
liquid_density = isotherm.adsorbate.liquid_density(isotherm.temperature)
surface_tension = isotherm.adsorbate.surface_tension(isotherm.temperature)
loading = isotherm.loading(branch=branch,loading_basis='molar',loading_unit='mmol')
pressure = isotherm.pressure(branch=branch, pressure_mode='relative')
if branch == 'des':
    loading = loading[::-1]
    pressure = pressure[::-1]

volume_adsorbed = loading * molar_mass / liquid_density / 1000
t_model = get_thickness_model(thickness_model)
k_model_args = {
    "meniscus_geometry": meniscus_geometry,
    "temperature": isotherm.temperature,
    "liquid_density": liquid_density,
    "adsorbate_molar_mass": molar_mass,
    "adsorbate_surface_tension": surface_tension
}
k_model = get_kelvin_model(kelvin_model, **k_model_args)

# Here is where you get the results
pore_widths, pore_dist, pore_vol_cum = psd_pygapsdh(
    volume_adsorbed, pressure, pore_geometry, t_model, k_model
)
```

Let me know if this helps.

**Comment by Loturest** [comment]
Very appreciated!

As to the negative values, I have checked the code and found that at some time,  "the volume desorbed from thinning" (thickness_factor  in the code ) will be larger than ads/des volume, resulting negative value. 

> def psd_pygapsdh()
>        # Calculate the volume desorbed from thinning of all pores previously emptied
>        thickness_factor = -d_thickness[i] * sum_area_factor
>        # Equation for pore volume, then add to the array
>       pore_volume = (d_volume[i] + thickness_factor) * ratio_factor

I also checked Micromeritics codes (https://github.com/RJC0514/micromeritics), it seems in such case, the pore_volume will be considered as 0.

**Comment by pauliacomi** [comment]
Hi again,

I've taken some time to get back to you on this, as I wanted to be fully sure. In short yes, the volume desorbed from thinning can be larger than the ads/des volume, though in my opinion this **should not be solved by setting it to zero**.

I've done some simulations to compare the idealized model output with a standard material, and it seems that the main source of the behaviour is that initial assumptions are wrong: either the function that is used to describe the thickness of the adsorbate inside the pores or the selected geometry simply do not accurately describe the process.

What then happens is that the pore size distribution calculation overshoots and generates negative values. Here is the difference between setting the meniscus geometry either to be cylindrical (cylinder pores)

![image](https://user-images.githubusercontent.com/9705355/175982670-0f96d711-53cf-4ce9-969c-b6262470e8da.png)

or to hemispherical (one-end open cylinder pores)

![image](https://user-images.githubusercontent.com/9705355/175982425-00af30df-6da3-44c7-aaab-23e5a54e980d.png)

So to me, negative values would signify bad model initial settings and that a user should think again about what parameters describes their system. To help highlight this I have added a warning that is thrown when this happens, see commit 3f9a635615c7696a14d557f9ef4a0d935b231b04

I have also added a new option to allow for manual selection of the meniscus geometry without having to use one of the base functions. You should now be able to do something like:

```
import pygaps.characterisation as pgc
pgc.psd_mesoporous(
    iso,
    "DH",
    branch="ads",
    pore_geometry="cylinder",
    meniscus_geometry="hemispherical",
    thickness_model="Harkins/Jura",
    verbose=True,
)
```

Finally, in the [pygaps GUI](https://github.com/pauliacomi/pyGAPS-gui), I added a graph like the one above, to highlight the match between the PSD model uptake and the actual isotherm, also hopefully to point out that there are some wrong assumptions.

Do you think this is appropriate? If so I will close this issue and make the changes part of a new release.

**Comment by Loturest** [comment]
Great. It is a better solution than just setting the value to 0.

**Comment by pauliacomi** [comment]
Great, thanks again for bringing this to my attention, it was interesting to think about.
