### ISSUE TITLE
Some adsorbate names unrecognised by CoolProp

### ISSUE THREAD

**Issue by sblanky** [pauliacomi/pyGAPS#34]
**Describe the bug**
`n-butane` is not recognised by CoolProp - it only recognises `n-Butane`. Is it possible to change the capitalisation? Understand if this is more of an issue on the CoolProp end, and can submit an issue there if so.

**To Reproduce**
```py
import pygaps.modelling as pgm
import pygaps.parsing as pgp

isotherm = pgp.isotherm_from_json('./docs/examples/data/isosteric/BAX 1500 - Isosteric Heat - 298.json')

model_isotherm = pgm.model_iso(isotherm, model='Langmuir')
p_triple = PropsSI('PTRIPLE', str(isotherm.adsorbate))
```

Throws error;

```
ValueError: Neither input to Props1SI [n-butane, PTRIPLE] is a valid fluid :: inputs were :"PTRIPLE","n-butane"
```

**Comment by pauliacomi** [comment]
Yes, CoolProp is very specific on the name of the compound.

Every (feasible) pyGAPS adsorbate has a property called `backend_name` which contains an approved CoolProp name, so you can use `isotherm.adsorbate.backend_name`.

**Comment by sblanky** [comment]
Thanks, that's painless.
