### ISSUE TITLE
Access isotherm parameters

### ISSUE THREAD

**Issue by yagzo** [pauliacomi/pyGAPS#35]
Would it be possible to make fitted isotherm parameters(e.g. for the Langmuir isotherm, 'n_m' and 'K' ) exposed directly to users. I know that I could print those parameters out by the "print_info" function and examine them one at a time, but for me I need to analyze many isotherms at once, It would make my job much easier if I could somehow access those fitted isotherm parameters directly from the <class: ModelIsotherm>.

**Comment by pauliacomi** [comment]
Hi @yagzo,

If you want to access the model parameters you can do:

```
iso.model.params
```

this is a dictionary with the raw model parameters.

**Comment by yagzo** [comment]
Thank you so much, this is exactly what I wanted.

**Comment by pauliacomi** [comment]
Great! You're more than welcome. :)
