### ISSUE TITLE
Quantachrome ".txt" files cannot be reliably parsed

### ISSUE THREAD

**Issue by k3ro** [pauliacomi/pyGAPS#40]
I try to load a isotherm from a .txt file, created from the Quantachrome software.
The Code is:

import pygaps.parsing as pgp
iso = pgp.isotherm_from_commercial('2022_01_27_CPG60_s3_77K_N2_CC_d2_M4_rescue (Isotherm).txt', "qnt", "txt")

but i get: ParsingError: Currently available manufacturers are ['bel', 'mic', '3p'])

The documentation says quantachrome is supported.
I'm confident i have the newest version installed.

**System (please complete the following information):**
 - OS: Windows
 - Python Version: 3.9.12
 - Toolchain: Anaconda Spyder

**Additional context**
I installed Anaconda/Spyder fresh just to use the package

**Comment by pauliacomi** [comment]
Hi there,

I had recently removed the Quantachrome file reading support as I found that many of their files are exported with odd errors that would not parse correctly.

Could you check if it can be transformed to an AIF using this parser?
[adsorptioninformationformat.com/raw2aif](http://adsorptioninformationformat.com/raw2aif)

Also, would you be able to share the raw file so that it may help me tune the parser? With more examples of errors I am confident I can tweak it correctly. Of course, only if it does not contain any confidential data etc.

Best,
Paul

**Comment by k3ro** [comment]
Thanks for the fast answer!
At first i was a little unsure about which file to upload. But i assume the parser wants the (Raw Data).txt
Strangely my particular file was not accepted. 
Unfortunatly i can not send you the file that does not work.
But i found out that in the line for the "Analysis gas:" the name had to many spaces and now it works.
i will try with the .aif thanks.


I know that depending on certain settings the .txt files may vary and have lines inserted here and there.
So maybe that is why it is so complicated to read the files.

**Edit**: But this .aif file can also not be loaded in python.
The error i get now is:

  File ~\Anaconda3\lib\site-packages\pygaps\parsing\aif.py:278 in isotherm_from_aif
    comp[1] = comp[1].replace('-1', '')

IndexError: list index out of range

**Comment by pauliacomi** [comment]
Yes exactly, I don't really know why their files have so many random errors in them, which means it is impossible to have them parsed.

May I ask since you are using a Quantachrome apparatus if it can export in other formats besides txt? Maybe they are easier to use.

Also let me know if I can help with anything else.

**Comment by pauliacomi** [comment]
@k3ro can you tell me the loading units of the AIF file?

**Comment by k3ro** [comment]
I think i can point out a few errors that are very common. Maybe that helps.

One can only export in .txt and .csv.
But these two differ.
The .txt has lots of information like non-ideality factor, mass, comments, void vol, degassing data and so on.
The .csv has only absolut Pressure, P0, Volume @STP and equilibration data.
I think in the .csv no lines are added. But of course not having the mass makes working with that file really tedious.

About the units in the AIF file, it is cc @STP.

Since i always work with .txt and i know the ~ 3 oddities that mess up the layout i will write my own code and just use pointIsotherms.

**Comment by pauliacomi** [comment]
Yes, it would be ideal if these extra data are kept in the files.
The AIF units should be in an "ideal" format to be read: either "x/y" or "x y^-1". It may help.

I will leave this issue open for now. If you happen to be able to share the resulting parsing code I'd be very grateful.

**Comment by k3ro** [comment]
I can share the code with you.
I also had a few more questions. 
I did send you a E-Mail.
Thanks so far for the really fast responses.

**Comment by pauliacomi** [comment]
Hi @k3ro, I've gone back to the quantachrome parser and it should now work well.
It was released in v4.3.0 
https://github.com/pauliacomi/pyGAPS/tree/v4.3.0
should be pip/conda installable in a few hours

**Comment by k3ro** [comment]
Really nice!
At first it didn't work for me because one has to write "txt-raw" and not what is recommended on the Webside:
https://pygaps.readthedocs.io/en/master/manual/parsing.html#parsing-manual-manufacturer
But because you taught me how to look at definitions i found that out myself! 


Apart from that it works as intended i think. It calculates relative pressures with p0 that are individual for each point. 
That's good.
But unfortunatly the Quantachrome software creates the raw files without giving the adsorptive name.
It does have  "Analysis Gas". But that is not actually the adsorptive but the name of the "folder/collection" of adsorptive parameters. It is like the name of a database entry that contains lots of information. 
And these entries are sometimes custom made, so you wouldn't know what to expect.
That is a problem because in my case the python software does not know which crosssectional area to take, since it reads for example: Nitrogen87K. 

In my case i will just change it after loading the data with this nice parser.
But unfortunatly i have never used objects.
Does a function exist for changing the adsorptiv?
Like converting the units?
Or can i just change the adsorptive of that object?
And would changing the adsorptive then change the crossectional area of that object?

**Comment by pauliacomi** [comment]
Whoops, good spot on the documentation I'll have to fix that!

Ok so it would be easy to change the adsorptive, once you loaded the isotherm:
```
isotherm = pg.isotherm_from....
isotherm.adsorbate = "nitrogen" # or "n2"
```
This would internally connect it to the correct pygaps adsorbate, with the cross-sectional area etc

**Comment by k3ro** [comment]
Sorry for the late response.
changing it like that worked for me, thanks a lot!
