### ISSUE TITLE
Circular import on pip install

### ISSUE THREAD

**Issue by sblanky** [pauliacomi/pyGAPS#48]
When I attempt to install a new version (after my edits) of pyGAPS, 

`pip install ~/pyGAPS/`

the modules in parsing `.csv` and `.json` throw an error such as;
`AttributeError: partially initialized module 'json' has no attribute 'loads' (most likely due to a circular import)`

or

`ImportError: cannot import name 'QUOTE_NONNUMERIC' from partially initialized module 'csv' (most likely due to a circular import) (/home/pcxtsbl/pyGAPS/src/pygaps/parsing/csv.py)`

I think this is because [they have the same external modules ](https://stackoverflow.com/questions/20082730/module-object-has-no-attribute-loads-while-parsing-json-using-python).

Changing names to, for example `.csv_` fixes this issue.

**Comment by pauliacomi** [comment]
I have not been able to replicate this on any system.

Any chance you can verify this in a fresh environment?

**Comment by sblanky** [comment]
Tried in a fresh environment, and can't get it to make this error. It may have been to do with the specific changes I made at some point, which I no longer need.

Sorry! Closing this.
