### ISSUE TITLE
Interpolation Error in isotherm.loading_at()

### ISSUE THREAD

**Issue by sblanky** [pauliacomi/pyGAPS#49]
When `isotherm.loading_at()` is called, sometimes a `ValueError` occurs at the limits of the isotherm. This appears to be due to conversion of the pressures to float16, which are not quite the same value as the original pressure data.

## Example

Variable file refers to attached aif file (annoyingly, in a .zip)
```py
import pygaps.parsing as pgp

isotherm = pgp.isotherm_from_aif(file)

pressure = isotherm.pressure(branch='ads', pressure_mode='relative')
loading = isotherm.loading_at(
            pressure=self.pressure,
            branch='ads',
            pressure_mode='relative',
            loading_unit='mol',
            loading_basis='molar',
            material_unit='g',
            material_basis='mass',
        )
```
This leads to the following Traceback;

```
loading = self.l_interpolator(pressure)
  File "/home/pcxtsbl/anaconda3/lib/python3.9/site-packages/pygaps/utilities/isotherm_interpolator.py", line 70, in __call__
    return self.interp_fun(data)
  File "/home/pcxtsbl/.local/lib/python3.9/site-packages/scipy/interpolate/_polyint.py", line 80, in __call__
    y = self._evaluate(x)
  File "/home/pcxtsbl/.local/lib/python3.9/site-packages/scipy/interpolate/_interpolate.py", line 752, in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)
  File "/home/pcxtsbl/.local/lib/python3.9/site-packages/scipy/interpolate/_interpolate.py", line 786, in _check_bounds
    raise ValueError("A value ({}) in x_new is above "
ValueError: A value (762.5309448200001) in x_new is above the interpolation range's maximum value (762.53094482).
```

As you can see, the only reason `x_new` is out of range is the addition of 5 bits to the original pressure value.

### Further information

Weirdly, this does not occur if we cut off the limits of the pressure list.
For example;

```py
pressure = isotherm.pressure()[1:-1]
loading = isotherm.loading_at(
            pressure=self.pressure,
            branch='ads',
            pressure_mode='relative',
            loading_unit='mol',
            loading_basis='molar',
            material_unit='g',
            material_basis='mass',
        )
```
Returns no error.

## Possible solution

Maybe the `IsothermInterpolater()` class should have its `__init__()` set up like this?

```py
def __init__(
        self,
        known_data,
        interp_data,
        interp_branch='ads',
        interp_kind='linear',
        interp_fill=True,
    ):
```
But perhaps you have a better way.

[aif.zip](https://github.com/pauliacomi/pyGAPS/files/11771594/aif.zip)

**Comment by pauliacomi** [comment]
Weird behaviour...

Under the hood, the `IsothermInterpolator` is a thin wrapper around `scipy.interpolate.interp1d` that adds caching for convenience. If `interp_fill` is anything besides `None`, its value is passed directly to the parameter `fill_value` of `interp1d`, which expects an array.

But then I tried going through `interp1d` with the raw data and it worked just fine.

I eventually found out that the error in precision is introduced in the on-the-fly conversion. As the isotherm is in an absolute pressure mode, and it is being asked to predict loading from a relative pressure, it performs a pressure conversion in the `loading_at` function. This seems to lower data precision for some reason.

Can you try?

``` python
isotherm.convert(pressure_mode='relative')
loading = isotherm.loading_at(
            pressure=self.pressure,
            branch='ads',
            pressure_mode='relative',
            loading_unit='mol',
            loading_basis='molar',
            material_unit='g',
            material_basis='mass',
)
```

Does it work?

**Comment by sblanky** [comment]
Yup, that works perfectly! Thanks Paul.

**Comment by pauliacomi** [comment]
I have been trying to get this working for a while, and it turns the code into a complicated hack.

- The loss of precision is inherent to floating point. Not much can be done here.
- Failing gracefully on the interpolator requires a lot of data introspection to get it right. The value to interpolate can be either a number or a list, with different behaviours needed for each: searching if the data point is close to the function edges for a single number, or searching the same thing for each array member for an array. 

It might be too much for an edge case. I suggest it is left as-is for now.

**Comment by sblanky** [comment]
That makes sense. Any idea why the on-the-fly conversion does this and `isotherm.conver()` doesn't?

**Comment by pauliacomi** [comment]
In the first case there is a double convert: absolute to relative when generating `pressure = isotherm.pressure(branch='ads', pressure_mode='relative')`, then relative to absolute in `isotherm.loading_at()`.

When `isotherm.convert()` is used, the interpolator is re-generated with the new values.

I will close this.
