### ISSUE TITLE
3P report file not parsing properly 

### ISSUE THREAD

**Issue by MyonicS** [pauliacomi/pyGAPS#50]
It looks like 3P changed something about the format of their .xlsx files, which made it fail when I tried to load my files. 
1) The sheet which is parsed as metadata is called 'Summary'  Changing its name to 'info' fixed it
2) In the isotherm sheet, a 'charge number' takes up the first row. Deleting the row fixed the issue

I'm using Version 10.03.09.04 of their analysis software
[3P_report_file.xlsx](https://github.com/pauliacomi/pyGAPS/files/11805707/3P_report_file.xlsx)

Since I saw the bath Temperature on the TO-DO List:
it's stored in 3P's own .jwgbt file format, but when exporting to xlsx that data is not stored. 

Here is a report file in both formats:
[3P_report_file.txt](https://github.com/pauliacomi/pyGAPS/files/11805711/3P_report_file.txt) (change extension from .jwgbt)
[3P_report_file.xlsx](https://github.com/pauliacomi/pyGAPS/files/11805707/3P_report_file.xlsx)

**Comment by pauliacomi** [comment]
Thanks for the heads-up. I will have a look into it.

The code for all parsing is maintained in a separate package I maintain: https://github.com/AIF-development-team/adsorption-file-parser

The .jwgbt file looks like an `xml` format. Unfortunately there's no parser for this implemented yet.

**Comment by pauliacomi** [comment]
Hi @MyonicS,

Sorry it took longer than expected to get to this. The parser has now been updated to be compatible with 3P Excel format changes. See https://github.com/AIF-development-team/adsorption-file-parser/commit/70e10387b980b59dc7fd5cce50b431889c2a6fcd
The feature will propagate to pyGAPS in next release.

I've attempted a few times to parse '.jwgbt' files. The 3P jwgbt format does not appear to contain uptake data. Instead it appears to contain information about the pressure and temperature of each dose. While theoretically, the amount adsorbed could be calculated from this data, this is outside the scope of a pure parser implementation. See below how the data is structured.

```
<Adsorb>
    <Item ID="0" Pd="-0.0000100000000000" Pcd="0.0663320194291271" PdT="0.0000000000000000" PcdT="26.1712062256809332" Day="2022-07-06" Time="11:32:03" P0="102.7410188143739873" Balance="1" SubIndex="0"/>
    <Item ID="1_1" Pd="2.2583126573586632" Pcd="0.0909305451248286" PdT="26.1886015106431671" PcdT="26.1886015106431671" Day="2022-07-06" Time="11:33:50" P0="102.7308462348363349" Balance="0" SubIndex="1"/>
    <Item ID="1_2" Pd="2.2827268482490268" Pcd="0.0991129356334646" PdT="26.2197299153124277" PcdT="26.2197299153124277" Day="2022-07-06" Time="11:35:55" P0="102.7267772030212853" Balance="0" SubIndex="2"/>
    <Item ID="1_3" Pd="0.1424161135271229" Pcd="0.0806922161436194" PdT="26.2197299153124277" PcdT="26.2188143739986259" Day="2022-07-06" Time="11:36:46" P0="102.7267772030212853" Balance="0" SubIndex="3"/>
    <Item ID="1_4" Pd="6.1422035248340574" Pcd="0.0991129356334646" PdT="26.2197299153124277" PcdT="26.2371252002746616" Day="2022-07-06" Time="11:38:36" P0="102.7308462348363349" Balance="0" SubIndex="4"/>
</Adsorb>
```

I've left a preliminary parser in the code, but inactive, in case data becomes available in a later format update.

Thanks again for highlighting this.
